### ISSUE TITLE
JOSS Paper - Invalid DOIs in the Reference

### ISSUE THREAD

**Issue by mengqi-z** [iosefa/PyForestScan#20]
Hi @iosefa,

I noticed a few missing and invalid DOIs in the latest version of your paper for the JOSS submission https://github.com/openjournals/joss-reviews/issues/7314. You can find the details here: https://github.com/openjournals/joss-reviews/issues/7314#issuecomment-2515213230.

To resolve the issue with the invalid DOIs, please remove the `https://doi.org/` prefix from the DOI links in your `paper.bib` file.

Thanks!

**Comment by iosefa** [comment]
Hello @mengqi-z 

I just made the change to fix the invalid DOIs and pushed to the paper branch. There is one invalid DOI that is actually valid -- the one about leafR: 

> ❌ MISSING DOIs
> 
> - 10.32614/cran.package.leafr may be a valid DOI for title: leafR: Calculates the Leaf Area Index (LAD) and Ot...

There was this thread about it earlier in the submission process: https://github.com/openjournals/joss-reviews/issues/7283#issuecomment-2375548957

So, I wont change that one as I believe that it is actually correct. 

Thank you!

**Comment by mengqi-z** [comment]
Hi @iosefa,

Thanks for revising the DOIs.

Regarding the DOI for `leafR`, it was missing from your Reference, not invalid. The JOSS editorial robot was able to locate the DOI, which matches the one listed on [`leafR`'s CRAN page](https://cran.r-project.org/web/packages/leafR/index.html): `10.32614/CRAN.package.leafR`. If you're using this version of `leafR` (v0.3.5), it would be appropriate to add this DOI in the citation, in addition to its url.

```
@report{dealmeidaLeafRCalculatesLeaf2021,
	title = {{leafR: Calculates the Leaf Area Index (LAD) and Other Related Functions}},
	url = {https://CRAN.R-project.org/package=leafR},
        doi = {10.32614/CRAN.package.leafR},
	type = {manual},
	author = {de Almeida, Danilo Roberti Alves and Stark, Scott Christopher and Silva, Carlos Alberto and Hamamura, Caio and Valbuena, Ruben},
	date = {2021},
}
```

Thanks!

**Comment by iosefa** [comment]
Hi @mengqi-z 

Ah, I see. I am using v0.3.5, so I have just updated the DOI and pushed to the paper branch. Thank you!

**Comment by mengqi-z** [comment]
Great! The references look good now! Thank you for addressing this.
