### ISSUE TITLE
Units for PAD/PAI

### ISSUE THREAD

**Issue by Ciaran1981** [iosefa/PyForestScan#21]
Hi,

A question rather than an issue. What are the units of the values outputted by the plant area density and index functions?

 
Thanks

**Comment by iosefa** [comment]
hi @Ciaran1981, thanks for your question! PAD is technically defined as the one-sided total plant area within a given volume. Thus, it has units of m^2/m^3 (dimensions of 1/Length). 

We calculate PAD for a given voxel based on the fraction of pulses entering and exiting the voxel. This fraction reflects the amount of plant material that attenuates the lidar pulses, which can be used as a proxy for the surface area of plant material within a voxel. Here is the documentation page for PAD: https://pyforestscan.sefa.ai/usage/forest-structure/pad/ and after re-reading it just now, I do think that it can be improved for clarity; will try to get to that sometime soon... Also, you may want to check out this paper: https://www.sciencedirect.com/science/article/abs/pii/S0378112718315561, which describes the methods in a little more detail. 

PAI is a dimensionless value, and so has no units. It is the sum of PAD across the vertical profile of the forest.

**Comment by Ciaran1981** [comment]
Great - thanks for your answer. Surely then a PAD value for a Voxel of 1 x 1 x1 could not exceed 1 if it is an area (ie m2) or indeed a volume?

Whereas the ouput from the code to generate PAD exceeds 1 with these parameters. Am I missing something?

**Comment by iosefa** [comment]
Hi, Ciaran

Thanks for your question, and sorry for taking so long to reply! It is totally possible for there to be a PAD > 1. There can be many layers of leaves in any orientation in a 1m^3 volume. For densely vegetated areas, I think it is common for PAD > 1. However, the units/dimensions may make this a little counterintuitive.

**Comment by Ciaran1981** [comment]
Ah right! Thanks very much!
